books/urls.py
from django.urls import path
from books import views

app_name="books"
urlpatterns = [
    path('', views.BooksModelView.as_view(), name='index'),

    path('book/', views.BookList.as_view(), name='book_list'),
    path('author/', views.AuthorList.as_view(), name='author_list'),
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),

    path('book/<int:pk>', views.BookDetail.as_view(), name='book_detail'),
    path('author/<int:pk>', views.AuthorDetail.as_view(), name='author_detail'),
    path('publisher/<int:pk>', views.PublisherDetail.as_view(), name='publisher_detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from mysite import views
urlpatterns = [
    path('', views.HomeView.as_view()),
    path('books/', include('books.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from polls import views


app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

books/models.py
from django.db import models

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE)
    publication_date = models.DateField()

    def __str__(self):
        return self.title

class Author(models.Model):
    salutation = models.CharField(max_length=100)
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.name

class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    website = models.URLField()

    def __str__(self):
        return self.name
        

polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self): #__str__ on Python 3
        return self.question_text+'ㅋㅋㄹㅃㅃ'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self): #__str__ on Python 3
        return self.choice_text+'ㅋㅋㄹㅃㅃ'

books/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView
from books.models import *

# TemplateView
class BooksModelView(TemplateView):
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        context = super(BooksModelView, self).get_context_data(**kwargs)
        context['object_list'] = ['book', 'Author', 'Publisher']
        return context

# ListView
class BookList(ListView):
    model = Book

class AuthorList(ListView):
    model = Author

class PublisherList(ListView):
    model = Author

# DetailView
class BookDetail(DetailView):
    model = Book

class AuthorDetail(DetailView):
    model = Author

class PublisherDetail(DetailView):
    model = Publisher

mysite/views.py
from django.views.generic.base import TemplateView


# TemplateView

class HomeView(TemplateView):

    template_name='home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['object_list'] = ['polls', 'books']

        return context

polls/views.py
from django.shortcuts import get_object_or_404, render
from polls.models import *
from django.http import HttpResponseRedirect
from django.urls import reverse
def index(request):
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}

    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(p.id, )))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

books/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}" />
    <title>{% block title %}My Amazing Site{% endblock %}</title>
</head>

<body>
    <div id="sidebar">
        {% block sidebar%}
        <ul>
            <li><a href="/">Project_Home</a></li>
            <li><a href="/admin/">Admin</a></li>
        </ul>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

books/templates/base_books.html
{% extends "base.html" %}

<title>{% block title %}Books Application Site{% endblock %}</title>

{% block sidebar %}
{{ block.super }}
<ul>
    <li><a href="/books/">Books_Home</a></li>
</ul>
{% endblock %}

books/templates/books/author_detail.html
{% extends "base_books.html" %}

{% block content %}

<h1>{{ object.name }}</h1>
<p>{{ ojbect.salutation }}</p>
<li>Email: {{ object.email }}</li>
{% endblock content %}

books/templates/books/author_list.html
{% extends "base_books.html" %}

{% block content %}
<h2>Author List</h2>
<ul>
    {% for author in object_list %}
    <li><a href="{% url 'books:author_detail' author.id %}">{{ author.name }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}

books/templates/books/book_detail.html
{% extends "base_books.html" %}

{% block content %}

<h1>{{ object.title }}</h1>
<br>
<li>Authors:
    {% for author in object.authors.all %}
    {{ author }}
    {% if not forloop.last %},{% else %}{% endif %}
    {% endfor %}
</li>
<li>Publisher: {{ object.publisher }}</li>
<li>Publication date: {{object.publication_date }}</li>
{% endblock content %}

books/templates/books/book_list.html
{% extends "base_books.html" %}

{% block content %}
<h2>Book List</h2>
<ul>
    {% for book in object_list %}
    <li><a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}

books/templates/books/index.html
{% extends 'base_books.html' %}

{% block content %}
<h2>Books Management System</h2>
<ul>
    {% for modelname in object_list %}
{% with urlvar="Books:"|add:modelname|lower|add:"_list" %}
    <li><a href="{% url urlvar %}">{{ modelname }}</a></li>
{% endwith %}
{% endfor %}
</ul>
{% endblock content %}

books/templates/books/publisher_detail.html
{% extends "base_books.html" %}

{% block content %}

<h1>{{ object.name }}</h1>
<p>{{ ojbect.website }}</p>
<li>Address: {{ object.address }}</li>
{% endblock content %}

books/templates/books/publisher_list.html
{% extends "base_books.html" %}

{% block content %}
<h2>Book List</h2>
<ul>
    {% for publisher in object_list %}
    <li><a href="{% url 'books:publisher_detail' publisher.id %}">{{ publisher.name }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}

books/templates/home.html
{% extends "base.html" %}

{% block content %}
<h2>성주의 Django App</h2>
<ul>
    {% for appname in object_list %}
    {% with urlvar=appname|add:":"|add:"index" %}
    <li><a href="{% url urlvar %}">{{ appname }}</a></li>
    {% endwith %}
    {% endfor %}
</ul>

{% endblock content %}

polls/templates/polls/detail.html
<h1>Question : {{ question.question_text }}</h1>
select it<br>


<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="제출" />
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:vote' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<!-- /polls/{{ question.id }}/ -->

polls/templates/polls/results.html
<h1>Question: {{ question.question_text }}<br/>Published at: {{ question.pub_date }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote Again?</a><br>
<a href="{% url 'polls:index' %} ">Main Page</a>